version: 2

project_name: gh-autoprofile

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/gh-autoprofile
    binary: gh-autoprofile
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/mdiloreto/gh-autoprofile/internal/cmd.Version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: binary
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

release:
  github:
    owner: mdiloreto
    name: gh-autoprofile
  draft: false
  prerelease: auto
  footer: |
    ## Upgrade notes

    This release includes security hardening for wrapper-mode token injection.

    Run these commands after upgrading:

    ```bash
    gh extension upgrade mdiloreto/gh-autoprofile
    gh autoprofile setup --migrate
    ```

    Then restart your shell (or source your shell rc file).
